version: "3"
services:
  deploy:
    container_name: algo-deploy
    build: ./
    environment:
      AWS_CONFIG_FILE: "/root/.aws/config"
    volumes:
      - ~/.aws/:/root/.aws/
      - ~/.ssh/:/root/.ssh/
      - $PWD:/code
